# Generated by Django 3.2.16 on 2022-11-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('region_id', models.IntegerField()),
                ('name_ar', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('center_lat', models.IntegerField()),
                ('center_lon', models.IntegerField()),
            ],
        ),
    ]
