# Generated by Django 3.2.16 on 2022-11-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cities',
            name='city_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
