# Generated by Django 3.2.16 on 2022-12-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20221128_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='city_id',
            new_name='id',
        ),
    ]
