# Generated by Django 3.2.16 on 2022-12-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_city_id_cities_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DB',
        ),
    ]
